[build]
  base = "."
  publish = "web/dist"
  command = "npm ci && npm run build:web"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/submit"
  to = "/.netlify/functions/submit"
  status = 200
  force = true

[[redirects]]
  from = "/api/config"
  to = "/.netlify/functions/config"
  status = 200
  force = true

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
